version: 0.1
phases:
  pre_build:
    commands:
      - echo "[Pre-build phase]"
      - terraform init
      - terraform plan
      - terraform apply -destroy -auto-approve
  build:
    commands:
      - echo "[Build phase]"
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo "[Post-build phase]"
