version: 0.1
phases:
  pre_build:
    commands:
      - echo "[Pre-build phase]"
      - terraform init
      - terraform import postgresql_role.application_role wagtail
      - terraform plan
  build:
    commands:
      - echo "[Build phase]"
      - terraform apply -auto-approve
  post_build:
    commands:
      - echo "[Post-build phase]"
